### ISSUE TITLE
Error 'KeyError:3'

### ISSUE THREAD

**Issue by lynnyi** [pachterlab/kma#16]
Please see my error trying to preprocess using kma

lynnyi⟫ python2.7 /home/lynnyi/R/x86_64-pc-linux-gnu-library/3.4/kma/pre-process/generate_introns.py --genome ~/genomes/Mus_musculus.GRCm38.dna.alt.fa  --gtf ~/genomes/Mus_musculus.GRCm38.91.gtf --extend 20 --out ~/introns    INFO: Reading in GTF: /home/lynnyi/genomes/Mus_musculus.GRCm38.91.gtf
INFO: Grouping transcripts by gene
INFO: Writing intron BED file: /home/lynnyi/introns/introns.bed
INFO: Computing intron-to-transcript compatability
INFO: Opening FASTA: /home/lynnyi/genomes/Mus_musculus.GRCm38.dna.alt.fa
INFO: Note: will take a while the first time it is opened.
Traceback (most recent call last):
  File "/home/lynnyi/R/x86_64-pc-linux-gnu-library/3.4/kma/pre-process/generate_introns.py", line 154, in <module>
    main()
  File "/home/lynnyi/R/x86_64-pc-linux-gnu-library/3.4/kma/pre-process/generate_introns.py", line 151, in main
    bed_to_introns(bed_out, args.genome, introns_out)
  File "/home/lynnyi/R/x86_64-pc-linux-gnu-library/3.4/kma/pre-process/generate_introns.py", line 55, in bed_to_introns
    seq = fasta[ref][int(start):int(stop)]
  File "/usr/local/lib/python2.7/dist-packages/pyfasta/fasta.py", line 128, in __getitem__
    c = self.index[i]
KeyError: '3'

**Comment by xf78** [comment]
I have the same problem，has anyone solved the problem yet?

**Comment by edwardfu11** [comment]
I have the same problem -- did this issue be resolved?  Thanks for sharing the solution.
Thanks!
-Eddie
